package main;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Auto;

public class AutoGui extends javax.swing.JFrame {

    private Auto egy;
    private int megadottKerekSzam;
//    private List<Auto> autok;

    public AutoGui() {
        initComponents();
        egy = new Auto();
        megadottKerekSzam = 0;
//        autok = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPujAuto = new javax.swing.JPanel();
        jRbUzemanyag = new javax.swing.JRadioButton();
        jRpDefekt = new javax.swing.JRadioButton();
        jLpotkrek = new javax.swing.JLabel();
        jBgarazsba = new javax.swing.JButton();
        jCbeinditva = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jlUjauto = new javax.swing.JLabel();
        jPgarazs = new javax.swing.JPanel();
        jCauotkgarazsba = new javax.swing.JComboBox<>();
        Jbmegy = new javax.swing.JButton();
        jBtankol = new javax.swing.JButton();
        jBtankol1 = new javax.swing.JButton();
        jLgarazs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTallapot = new javax.swing.JTextArea();
        jLautoaAllapota = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPujAuto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jRbUzemanyag.setText("üzemanyag");
        jRbUzemanyag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbUzemanyagActionPerformed(evt);
            }
        });

        jRpDefekt.setText("defekt");
        jRpDefekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRpDefektActionPerformed(evt);
            }
        });

        jLpotkrek.setText("pótkerék:");

        jBgarazsba.setText("garázsba");
        jBgarazsba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgarazsbaActionPerformed(evt);
            }
        });

        jCbeinditva.setText("beinditva");
        jCbeinditva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbeinditvaActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPujAutoLayout = new javax.swing.GroupLayout(jPujAuto);
        jPujAuto.setLayout(jPujAutoLayout);
        jPujAutoLayout.setHorizontalGroup(
            jPujAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPujAutoLayout.createSequentialGroup()
                .addGroup(jPujAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPujAutoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPujAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPujAutoLayout.createSequentialGroup()
                                .addGroup(jPujAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRbUzemanyag, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRpDefekt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPujAutoLayout.createSequentialGroup()
                                .addComponent(jLpotkrek, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPujAutoLayout.createSequentialGroup()
                        .addComponent(jCbeinditva, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jBgarazsba)))
                .addContainerGap())
        );
        jPujAutoLayout.setVerticalGroup(
            jPujAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPujAutoLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jRbUzemanyag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRpDefekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPujAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLpotkrek)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPujAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbeinditva)
                    .addComponent(jBgarazsba))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jlUjauto.setText("Új autó");

        jPgarazs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCauotkgarazsba.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jCauotkgarazsba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCauotkgarazsbaActionPerformed(evt);
            }
        });

        Jbmegy.setText("megy");
        Jbmegy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbmegyActionPerformed(evt);
            }
        });

        jBtankol.setText("tankol");
        jBtankol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtankolActionPerformed(evt);
            }
        });

        jBtankol1.setText("kerékcsere");
        jBtankol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtankol1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPgarazsLayout = new javax.swing.GroupLayout(jPgarazs);
        jPgarazs.setLayout(jPgarazsLayout);
        jPgarazsLayout.setHorizontalGroup(
            jPgarazsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPgarazsLayout.createSequentialGroup()
                .addGroup(jPgarazsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPgarazsLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jCauotkgarazsba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPgarazsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Jbmegy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtankol))
                    .addGroup(jPgarazsLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jBtankol1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPgarazsLayout.setVerticalGroup(
            jPgarazsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPgarazsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jCauotkgarazsba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPgarazsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jbmegy)
                    .addComponent(jBtankol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtankol1)
                .addGap(10, 10, 10))
        );

        jLgarazs.setText("Garázs");

        jTallapot.setColumns(20);
        jTallapot.setRows(5);
        jScrollPane1.setViewportView(jTallapot);

        jLautoaAllapota.setText("Autó állapota:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPujAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlUjauto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPgarazs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLgarazs, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLautoaAllapota, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUjauto)
                    .addComponent(jLgarazs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPgarazs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPujAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLautoaAllapota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCbeinditvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbeinditvaActionPerformed
        if (jCbeinditva.isSelected()) {
            if (!egy.isDefekt() & egy.isUzemanyag()) {
                egy = new Auto(egy.isUzemanyag(), true, megadottKerekSzam);
                jTallapot.setText("Beinditva");
                System.out.println(egy.isUzemanyag());
                System.out.println(egy.isBeinditva());
            } else if (!egy.isDefekt() & !egy.isUzemanyag()) {
                egy = new Auto(egy.isUzemanyag(), false, megadottKerekSzam);
                jTallapot.setText("Nincs beinditva. Nincs üzemanyag");
                System.out.println(egy.isUzemanyag());
                System.out.println(egy.isBeinditva());
            } else if (egy.isDefekt() & !egy.isUzemanyag()) {
                egy = new Auto(egy.isUzemanyag(), false, megadottKerekSzam);
                jTallapot.setText("Nincs beinditva. Defekt van");
                System.out.println(egy.isUzemanyag());
                System.out.println(egy.isBeinditva());
            } else if (egy.isDefekt() & !egy.isUzemanyag()) {
                egy = new Auto(egy.isUzemanyag(), false, megadottKerekSzam);
                jTallapot.setText("Nincs beinditva. Defekt van és nincs üzemanyag");
                System.out.println(egy.isUzemanyag());
                System.out.println(egy.isBeinditva());
            }

        } else {
            egy = new Auto(egy.isDefekt(), false, megadottKerekSzam);
            jTallapot.setText("");
        }
    }//GEN-LAST:event_jCbeinditvaActionPerformed

    private void jBtankolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtankolActionPerformed
        if (!egy.isBeinditva()) {
            if (egy.isUzemanyag()) {
                egy.tankol();
                jTallapot.setText("Tankolva");
                System.out.println(egy.isUzemanyag());
            } else if (!egy.isUzemanyag()) {
                egy.tankol();
                jTallapot.setText("Van üzemanyag");

            }

        } else {
            jTallapot.setText("Nem tudsz tankolni be van inditva");
        }


    }//GEN-LAST:event_jBtankolActionPerformed

    private void jRbUzemanyagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbUzemanyagActionPerformed
        if (jRbUzemanyag.isSelected()) {
            if (egy.isUzemanyag()) {
                jTallapot.setText("Van üzemanyag");
                System.out.println(egy.isUzemanyag());
            } else if (!egy.isUzemanyag()) {
                jTallapot.setText("Nincs üzemanyag");
            }

        } else {
            egy = new Auto(false, false);
            jTallapot.setText(" ");
        }
    }//GEN-LAST:event_jRbUzemanyagActionPerformed

    private void jRpDefektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRpDefektActionPerformed
        if (jRpDefekt.isSelected()) {
            if (!egy.isDefekt()) {
                JOptionPane.showMessageDialog(rootPane, "Defektett kaptál");
                egy.defektetKap();
                jTallapot.setText("Defekt");
                System.out.println(egy.isDefekt());
            }
        } else {
            egy.kerekCsere();
            jTallapot.setText(" ");
            System.out.println(egy.isDefekt());
        }

    }//GEN-LAST:event_jRpDefektActionPerformed

    private void jBgarazsbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgarazsbaActionPerformed
//        Auto auto = new Auto(egy.isUzemanyag(), egy.isBeinditva(), egy.isDefekt(), megadottKerekSzam);
//        autok.add(auto);
//        String info = "Auto #" + autok.size() + " - Üzemanyag: " + auto.isUzemanyag() + ", Beindítva: " + auto.isBeinditva() + ", Defekt: " + auto.isDefekt() + ", Pótkerék: " + auto.getPotkerek();
//        jCauotkgarazsba.addItem(info);


    }//GEN-LAST:event_jBgarazsbaActionPerformed

    private void jCauotkgarazsbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCauotkgarazsbaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCauotkgarazsbaActionPerformed

    private void JbmegyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbmegyActionPerformed
        if (egy.isBeinditva() & !egy.isDefekt() & egy.isUzemanyag()) {
            egy.megy();
            jTallapot.setText("Megy");
        } else if (!egy.isBeinditva() & !egy.isDefekt() & egy.isUzemanyag()) {
            egy.megy();
            jTallapot.setText("Nem megy, nincs beinidtva");
        } else if (egy.isBeinditva() & egy.isDefekt() & egy.isUzemanyag()) {
            egy.megy();
            jTallapot.setText("Nem megy, defekt van");
        } else if (egy.isBeinditva() & !egy.isDefekt() & !egy.isUzemanyag()) {
            egy.megy();
            jTallapot.setText("Nem megy, nincs üzemanyag");
        } else if (!egy.isBeinditva() & !egy.isDefekt() & !egy.isUzemanyag()) {
            egy.megy();
            jTallapot.setText("Nem megy, nincs semmi");
        }


    }//GEN-LAST:event_JbmegyActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        megadottKerekSzam = jComboBox1.getSelectedIndex();
        egy = new Auto(egy.isBeinditva(), egy.isUzemanyag(), megadottKerekSzam);
        jTallapot.setText("Ennyi pótkerék van: " + megadottKerekSzam);


    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jBtankol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtankol1ActionPerformed
        if (egy.isDefekt()) {
            if (megadottKerekSzam <= 0) {
                jTallapot.setText("Nincs több pótkerék");
            } else {
                egy.kerekCsere();
                jTallapot.setText("Kerék cserélve");
                megadottKerekSzam--;
                System.out.println(egy.isDefekt());
            }

        } else if (!egy.isDefekt()) {
            jTallapot.setText("Nem kell keleket cserélni");
        }
    }//GEN-LAST:event_jBtankol1ActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbmegy;
    private javax.swing.JButton jBgarazsba;
    private javax.swing.JButton jBtankol;
    private javax.swing.JButton jBtankol1;
    private javax.swing.JComboBox<String> jCauotkgarazsba;
    private javax.swing.JCheckBox jCbeinditva;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLautoaAllapota;
    private javax.swing.JLabel jLgarazs;
    private javax.swing.JLabel jLpotkrek;
    private javax.swing.JPanel jPgarazs;
    private javax.swing.JPanel jPujAuto;
    private javax.swing.JRadioButton jRbUzemanyag;
    private javax.swing.JRadioButton jRpDefekt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTallapot;
    private javax.swing.JLabel jlUjauto;
    // End of variables declaration//GEN-END:variables

}
